### ISSUE TITLE
Install ZenHub

### ISSUE THREAD

**Issue by lavaoutsiders** [MathijsHubrechtsen/DRAMA-Compiler#2]
To improve the collaboration and issue tracking efficiency, install the ZenHub as your chrome extension.
For further details, please go to [https://www.zenhub.com/](url).

**Comment by lavaoutsiders** [comment]
Please close this issue if you've already installed `Zenhub`

**Comment by Frostielocks** [comment]
I'm adding a comment here just to clear up any possible confusion future contributors might have.
Using zenhub is not necessary, I do not believe it is necessary for a project of this scale.
