### ISSUE TITLE
Provide a good README

### ISSUE THREAD

**Issue by Wh1spr** [MathijsHubrechtsen/DRAMA-Compiler#4]

**Comment by Wh1spr** [comment]
I would suggest using [this](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) as an example.

**Comment by lavaoutsiders** [comment]
Yo’ all

I’m half back from vacation and I apologies for all inconvenience that was made. :(
The required discord server has been created at the following address.
https://discordapp.com/invite/GS23G9U
Also, the Ubuntu server was also created at server.t-zand.be, if you need access, simply request the private key and SSH to server.t-zand.be or 35.157.247.65 using your own credentials .

What I also think, is that providing an effective web application which can hosted at above server, can drastically improve the usability of this application.

Greetings and meet you very soon
(I do not have access to messenger/ facebook/ GitHub/ Google, ... right now)

Li
发件人: Wh1spr<mailto:notifications@github.com>
发送时间: 2017年7月29日 18:37
收件人: MathijsHubrechtsen/DRAMA-Compiler<mailto:DRAMA-Compiler@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [MathijsHubrechtsen/DRAMA-Compiler] Provide a good README (#4)


I would suggest using this<https://gist.github.com/PurpleBooth/109311bb0361f32d87a2> as an example.

―

**Comment by Frostielocks** [comment]
Adding a comment so that future contributors know why this issue was closed. Wh1spr's suggestion was great and I made a README using [his linked template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) as soon as I could.
